spring:
  data:
    jpa.repositories.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        ddl-auto: none
        use-new-id-generator-mappings: false
        default_schema: @project.artifactId@
      show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: @project.artifactId@
    baseline-on-migrate: true
  datasource:
    driverclassname: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/@project.artifactId@
    username: postgres
    password: mysecretpassword
    initialize: true

scheduler:
  enable: true
  documentsSize: 500
  fixedDelayInMillis: 1000

pooling:
  url: https://apidev.meep.me/tripplan/api/v1/routers/lisboa/resources?lowerLeftLatLon=38.711046,-9.160096&upperRightLatLon=38.739429,-9.137115&companyZoneIds=545,467,473